language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t heohyoyeong/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true heohyoyeong/react-test-app npm test

after_success:
  - docker build -t heohyoyeong/docker-frontend ./frontend
  - docker build -t heohyoyeong/docker-backend ./backend
  - docker build -t heohyoyeong/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push heohyoyeong/docker-frontend
  - docker push heohyoyeong/docker-backend
  - docker push heohyoyeong/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-us-west-2-665683613775
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY