version: "3"
services:
  frontend:
    image: "heohyoyeong/docker-frontend"
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_litit: 128m

  nginx: 
    image: "heohyoyeong/docker-nginx"
    restart: always
    # build:
    #   dockerfile: Dockerfile
    #   context: ./nginx
    ports: 
      - "80:80"
    link:
      - frontend
      - backend
    mem_litit: 128m


  backend:
    image: "heohyoyeong/docker-backend"
    # build: 
    #   dockerfile: Dockerfile.dev
    #   context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment: 
      MYSQL_HOST: docker-fullstack-mysql.cqxxqploz0kp.us-west-2.rds.amazonaws.com
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: heohyoyeong1993
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306   
    mem_litit: 128m
  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports: 
  #     - "3308:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment: 
  #     MYSQL_ROOT_PASSWORD: 1q2w3e4r!!
  #     MYSQL_DATABASE: myapp
