version: "2.4"
services:
  frontend:
    image: "heohyoyeong/docker-frontend"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit : 128m  
    
  nginx: 
    image: "heohyoyeong/docker-nginx"
    restart: always
    ports: 
      - "80:80"
    links:
      - frontend
      - backend
    mem_limit : 128m  

  backend:
    image: "heohyoyeong/docker-backend"
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment: 
      MYSQL_HOST: docker-fullstack-mysql.cqxxqploz0kp.us-west-2.rds.amazonaws.com
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: heohyoyeong1993
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306  
    mem_limit : 128m  

